/**
 * Custom Worker entry for the web app.
 *
 * Wraps the OpenNext-generated worker and same-origin proxies `/realtime/*`
 * (HTTP and WebSocket upgrades) to the realtime Worker over a service binding,
 * so guest cookies stay first-party and no CORS is needed in production.
 */

// Generated by `opennextjs-cloudflare build`.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- build artifact
// @ts-ignore -- file exists after the OpenNext build
import next from "./.open-next/worker.js";

const REALTIME_PREFIX = "/realtime";
const TRUSTED_PROXY_ORIGIN = "https://hivemind-web.internal";

interface NextWorker {
  fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<Response> | Response;
}

function isOwnOrigin(origin: string | null, requestUrl: URL): boolean {
  if (origin === null) {
    // Same-origin navigations and some WebSocket clients omit Origin.
    return true;
  }
  try {
    return new URL(origin).origin === requestUrl.origin;
  } catch {
    return false;
  }
}

export default {
  async fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);
    if (
      url.pathname === REALTIME_PREFIX ||
      url.pathname.startsWith(`${REALTIME_PREFIX}/`)
    ) {
      if (!isOwnOrigin(request.headers.get("origin"), url)) {
        return Response.json({ error: "invalid-origin" }, { status: 403 });
      }
      const headers = new Headers(request.headers);
      headers.set("origin", TRUSTED_PROXY_ORIGIN);
      return env.REALTIME.fetch(new Request(request, { headers }));
    }
    return (next as NextWorker).fetch(request, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;
