# generated by datamodel-codegen:
#   filename:  attempt.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import product_mode


class Attempt(BaseModel):
    """
    Attempt
    """

    model_config = ConfigDict(extra="forbid")
    course_version: Annotated[
        str | None, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ] = None
    """
    Semantic version major.minor.patch
    """
    finished_at: Annotated[
        str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ] = None
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    hints: list[Hint]
    id: Annotated[str, Field(pattern="^HM-ATT-\\d{6,}$")]
    lab_session_id: Annotated[str | None, Field(pattern="^HM-LAB-\\d{6}$")] = None
    learner_id: Annotated[str, Field(pattern="^HM-LRN-\\d{6}$")]
    lesson_id: Annotated[str | None, Field(pattern="^HM-LESSON-[a-z0-9-]+-\\d{2}$")] = None
    mode: product_mode.ProductMode
    problem_instance_id: Annotated[str | None, Field(pattern="^HM-PI-\\d{6,}$")] = None
    skill_versions: list[SkillVersion]
    started_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    status: Status


class Hint(BaseModel):
    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    tier: Tier


class SkillVersion(BaseModel):
    model_config = ConfigDict(extra="forbid")
    skill_id: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Status(StrEnum):
    in_progress = "in_progress"
    submitted = "submitted"
    graded = "graded"
    abandoned = "abandoned"
    expired = "expired"


class Tier(StrEnum):
    minor = "minor"
    strong = "strong"
    solution = "solution"
