# generated by datamodel-codegen:
#   filename:  block_node.json

from __future__ import annotations

from enum import IntEnum, StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import inline_node


class BlockNode1(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    children: list[
        inline_node.InlineNode1
        | inline_node.InlineNode2
        | inline_node.InlineNode3
        | inline_node.InlineNode4
        | inline_node.InlineNode5
        | inline_node.InlineNode6
        | inline_node.InlineNode7
        | inline_node.InlineNode8
    ]
    kind: Literal["heading"]
    level: Level


class BlockNode10(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    kind: Literal["thematic_break"]


class BlockNode2(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    children: list[
        inline_node.InlineNode1
        | inline_node.InlineNode2
        | inline_node.InlineNode3
        | inline_node.InlineNode4
        | inline_node.InlineNode5
        | inline_node.InlineNode6
        | inline_node.InlineNode7
        | inline_node.InlineNode8
    ]
    kind: Literal["paragraph"]


class BlockNode3(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    items: list[
        list[
            BlockNode1
            | BlockNode2
            | BlockNode3
            | BlockNode4
            | BlockNode5
            | BlockNode6
            | BlockNode7
            | BlockNode8
            | BlockNode9
            | BlockNode10
        ]
    ]
    kind: Literal["list"]
    ordered: bool


class BlockNode4(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    caption: str | None = None
    code: str
    kind: Literal["code_block"]
    language: Annotated[str | None, Field(min_length=1)] = None


class BlockNode5(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    header: list[
        list[
            inline_node.InlineNode1
            | inline_node.InlineNode2
            | inline_node.InlineNode3
            | inline_node.InlineNode4
            | inline_node.InlineNode5
            | inline_node.InlineNode6
            | inline_node.InlineNode7
            | inline_node.InlineNode8
        ]
    ]
    kind: Literal["table"]
    rows: list[
        list[
            list[
                inline_node.InlineNode1
                | inline_node.InlineNode2
                | inline_node.InlineNode3
                | inline_node.InlineNode4
                | inline_node.InlineNode5
                | inline_node.InlineNode6
                | inline_node.InlineNode7
                | inline_node.InlineNode8
            ]
        ]
    ]


class BlockNode6(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    callout: Callout
    children: list[
        BlockNode1
        | BlockNode2
        | BlockNode3
        | BlockNode4
        | BlockNode5
        | BlockNode6
        | BlockNode7
        | BlockNode8
        | BlockNode9
        | BlockNode10
    ]
    kind: Literal["callout"]
    title: str | None = None


class BlockNode7(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    caption: str | None = None
    format: Format
    kind: Literal["diagram"]
    source: Annotated[str, Field(min_length=1)]


class BlockNode8(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    kind: Literal["question"]
    question_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]


class BlockNode9(BaseModel):
    """
    Lesson block render node
    """

    model_config = ConfigDict(extra="forbid")
    children: list[
        BlockNode1
        | BlockNode2
        | BlockNode3
        | BlockNode4
        | BlockNode5
        | BlockNode6
        | BlockNode7
        | BlockNode8
        | BlockNode9
        | BlockNode10
    ]
    exercise: Exercise
    kind: Literal["exercise"]
    title: Annotated[str, Field(min_length=1)]


class Callout(StrEnum):
    note = "note"
    tip = "tip"
    warning = "warning"
    misconception = "misconception"
    prediction = "prediction"


class Exercise(StrEnum):
    guided = "guided"
    demonstration = "demonstration"
    independent = "independent"


class Format(StrEnum):
    ascii = "ascii"
    mermaid = "mermaid"


class Level(IntEnum):
    integer_3 = 3
    integer_4 = 4


BlockNode1.model_rebuild()
BlockNode3.model_rebuild()
BlockNode6.model_rebuild()
BlockNode9.model_rebuild()
