# generated by datamodel-codegen:
#   filename:  capability_descriptor.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import execution_class


class CapabilityDescriptor(BaseModel):
    """
    Capability with execution class
    """

    model_config = ConfigDict(extra="forbid")
    class_: Annotated[execution_class.ExecutionClass, Field(alias="class")]
    description: Annotated[str, Field(max_length=300, min_length=1)]
    id: Annotated[
        str,
        Field(
            max_length=96,
            min_length=3,
            pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$",
            title="Capability",
        ),
    ]
    """
    Capability id, e.g. shell.linux, network.containerlab, routing.frr
    """
