# generated by datamodel-codegen:
#   filename:  capability.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class Capability(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=96,
            min_length=3,
            pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$",
            title="Capability",
        ),
    ]
    """
    Capability id, e.g. shell.linux, network.containerlab, routing.frr
    """
