# generated by datamodel-codegen:
#   filename:  career_profile.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class CareerProfile(BaseModel):
    """
    Learner career target
    """

    model_config = ConfigDict(extra="forbid")
    active: bool
    learner_id: Annotated[str, Field(pattern="^HM-LRN-\\d{6}$")]
    notes: str | None = None
    """
    Markdown text, rendered by the web app
    """
    role_profile_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    role_profile_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    set_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
