# generated by datamodel-codegen:
#   filename:  check_spec.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class CheckSpec(BaseModel):
    """
    Deterministic check
    """

    model_config = ConfigDict(extra="forbid")
    command: Annotated[list[str], Field(min_length=1)]
    expect: Expect | Expect1 | Expect2 | Expect3
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    timeout_seconds: Annotated[int, Field(ge=1, le=600)]


class Expect(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["exit_code"]
    value: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class Expect1(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["stdout_contains"]
    value: Annotated[str, Field(min_length=1)]


class Expect2(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["stdout_matches"]
    pattern: Annotated[str, Field(min_length=1)]


class Expect3(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["stdout_json_equals"]
    path: Annotated[str, Field(min_length=1)]
    value: Any
