# generated by datamodel-codegen:
#   filename:  claim.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Claim(BaseModel):
    """
    Factual claim with provenance
    """

    model_config = ConfigDict(extra="forbid")
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    lesson_id: Annotated[str, Field(pattern="^HM-LESSON-[a-z0-9-]+-\\d{2}$")]
    notes: str | None = None
    """
    Markdown text, rendered by the web app
    """
    source_ids: Annotated[list[SourceId], Field(min_length=1)]
    statement: Annotated[str, Field(max_length=1000, min_length=1)]
    verification: Verification
    verified_at: Annotated[
        str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ] = None
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    verified_by: Annotated[str | None, Field(max_length=120)] = None


class SourceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    """
    Source id, e.g. src.iproute2.ip-route
    """


class Verification(StrEnum):
    unverified = "unverified"
    verified = "verified"
    conflict = "conflict"
    rejected = "rejected"
