# generated by datamodel-codegen:
#   filename:  competency.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import definition_status


class Competency(BaseModel):
    """
    Competency
    """

    model_config = ConfigDict(extra="forbid")
    category: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    description: str
    """
    Markdown text, rendered by the web app
    """
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    name: Annotated[str, Field(max_length=160, min_length=1)]
    skills: Annotated[list[Skill], Field(min_length=1)]
    status: definition_status.DefinitionStatus
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Skill(BaseModel):
    model_config = ConfigDict(extra="forbid")
    min_mastery: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    skill_id: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
    weight: Annotated[float, Field(ge=0.0, le=1.0)]
