# generated by datamodel-codegen:
#   filename:  confidence.json

from __future__ import annotations

from enum import StrEnum


class Confidence(StrEnum):
    """
    Confidence tier beside every score
    """

    low = "low"
    medium = "medium"
    high = "high"
