# generated by datamodel-codegen:
#   filename:  connection_state.json

from __future__ import annotations

from enum import StrEnum


class ConnectionState(StrEnum):
    """
    Session connection state
    """

    connecting = "connecting"
    synchronizing = "synchronizing"
    online = "online"
    offline = "offline"
    finished = "finished"
