# generated by datamodel-codegen:
#   filename:  content_bundle.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import course_manifest, lesson, module, skill_definition, source_record


class ContentBundle(BaseModel):
    """
    Compiled content bundle
    """

    model_config = ConfigDict(extra="forbid")
    bundle_format: Literal[1]
    content_hash: Annotated[str, Field(pattern="^[a-f0-9]{64}$")]
    courses: list[course_manifest.CourseManifest]
    generated_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    git_commit: Annotated[str | None, Field(pattern="^[a-f0-9]{7,40}$")] = None
    lessons: list[lesson.Lesson]
    modules: list[module.Module]
    skills: list[skill_definition.SkillDefinition]
    sources: list[source_record.SourceRecord]
