# generated by datamodel-codegen:
#   filename:  content_version.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ContentVersion(BaseModel):
    """
    Immutable published content version
    """

    model_config = ConfigDict(extra="forbid")
    content_hash: Annotated[str, Field(pattern="^[a-f0-9]{64}$")]
    counts: Counts
    course_ids: list[CourseId]
    created_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    git_commit: Annotated[str | None, Field(pattern="^[a-f0-9]{7,40}$")] = None
    id: Annotated[str, Field(pattern="^HM-CV-\\d{4,}$")]
    note: Annotated[str | None, Field(max_length=500)] = None
    published_by: Annotated[str, Field(max_length=120, min_length=1)]


class Counts(BaseModel):
    model_config = ConfigDict(extra="forbid")
    courses: Annotated[int, Field(ge=0, le=9007199254740991)]
    lessons: Annotated[int, Field(ge=0, le=9007199254740991)]
    modules: Annotated[int, Field(ge=0, le=9007199254740991)]
    skills: Annotated[int, Field(ge=0, le=9007199254740991)]
    sources: Annotated[int, Field(ge=0, le=9007199254740991)]


class CourseId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    """
    Course id slug, e.g. linux-networking
    """
