# generated by datamodel-codegen:
#   filename:  course_manifest.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import capability, definition_status


class CourseManifest(BaseModel):
    """
    Course manifest
    """

    model_config = ConfigDict(extra="forbid")
    capabilities: list[capability.Capability]
    domain: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    id: Annotated[str, Field(pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    """
    Course id slug, e.g. linux-networking
    """
    module_ids: Annotated[list[ModuleId], Field(min_length=1)]
    prerequisite_course_ids: list[PrerequisiteCourseId]
    skill_ids: Annotated[list[SkillId], Field(min_length=1)]
    source_ids: list[SourceId]
    status: definition_status.DefinitionStatus
    summary: Annotated[str, Field(max_length=600, min_length=1)]
    title: Annotated[str, Field(max_length=200, min_length=1)]
    tracks: list[Track]
    uses_labs: bool
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class ModuleId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9-]+\\.[a-z0-9-]+$")]
    """
    Module id <course>.<slug>, e.g. linux-networking.routing
    """


class PrerequisiteCourseId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    """
    Course id slug, e.g. linux-networking
    """


class SkillId(RootModel[str]):
    root: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """


class SourceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    """
    Source id, e.g. src.iproute2.ip-route
    """


class Track(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
