# generated by datamodel-codegen:
#   filename:  create_session_request.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class CreateSessionRequest(BaseModel):
    """
    Create a lab session
    """

    model_config = ConfigDict(extra="forbid")
    archetype: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    parameters: dict[str, Any] | None = None
    problem_instance_id: Annotated[str | None, Field(pattern="^HM-PI-\\d{6,}$")] = None
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
    ttl_minutes: Annotated[int | None, Field(ge=1, le=9007199254740991)] = None
