# generated by datamodel-codegen:
#   filename:  definition_status.json

from __future__ import annotations

from enum import StrEnum


class DefinitionStatus(StrEnum):
    """
    Versioned definition lifecycle
    """

    active = "active"
    deprecated = "deprecated"
    archived = "archived"
