# generated by datamodel-codegen:
#   filename:  destroy_request.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class DestroyRequest(BaseModel):
    """
    Destroy request
    """

    model_config = ConfigDict(extra="forbid")
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    reason: Reason


class Reason(StrEnum):
    completed = "completed"
    expired = "expired"
    requested = "requested"
    failed = "failed"
    orphaned = "orphaned"
