# generated by datamodel-codegen:
#   filename:  destroy_job.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class DestroyJob(BaseModel):
    """
    Destroy a lab
    """

    model_config = ConfigDict(extra="forbid")
    job_id: Annotated[
        str,
        Field(pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"),
    ]
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    reason: Reason
    type: Literal["job.destroy"]


class Reason(StrEnum):
    completed = "completed"
    expired = "expired"
    requested = "requested"
    failed = "failed"
    orphaned = "orphaned"
