# generated by datamodel-codegen:
#   filename:  error_event.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class ErrorEvent(BaseModel):
    """
    Error event
    """

    model_config = ConfigDict(extra="forbid")
    code: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    job_id: Annotated[
        str | None,
        Field(pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"),
    ] = None
    lab_session_id: Annotated[str | None, Field(pattern="^HM-LAB-\\d{6}$")] = None
    message: Annotated[str, Field(max_length=2000)]
    retryable: bool
    type: Literal["event.error"]
