# generated by datamodel-codegen:
#   filename:  evidence.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import hint_tier


class Evidence(BaseModel):
    """
    Mastery evidence
    """

    model_config = ConfigDict(extra="forbid")
    attempt_id: Annotated[str, Field(pattern="^HM-ATT-\\d{6,}$")]
    blind: bool
    correctness: Annotated[float, Field(ge=0.0, le=1.0)]
    created_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    difficulty: Annotated[int, Field(ge=1, le=5)]
    id: Annotated[str, Field(pattern="^HM-EV-\\d{6,}$")]
    independence: hint_tier.HintTier
    kind: Kind
    learner_id: Annotated[str, Field(pattern="^HM-LRN-\\d{6}$")]
    skill_id: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
    skill_version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Kind(StrEnum):
    lesson_question = "lesson_question"
    guided_lab = "guided_lab"
    practice_problem = "practice_problem"
    challenge = "challenge"
    blind_incident = "blind_incident"
    interview = "interview"
    project = "project"
