# generated by datamodel-codegen:
#   filename:  exec_request.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ExecRequest(BaseModel):
    """
    Command execution request
    """

    model_config = ConfigDict(extra="forbid")
    command: Annotated[list[str], Field(min_length=1)]
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    timeout_seconds: Annotated[int, Field(ge=1, le=9007199254740991)]
