# generated by datamodel-codegen:
#   filename:  execution_mode.json

from __future__ import annotations

from enum import StrEnum


class ExecutionMode(StrEnum):
    """
    AI execution mode
    """

    external = "external"
    api = "api"
