# generated by datamodel-codegen:
#   filename:  exec_job.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class ExecJob(BaseModel):
    """
    Run a command on a node
    """

    model_config = ConfigDict(extra="forbid")
    command: Annotated[list[str], Field(min_length=1)]
    job_id: Annotated[
        str,
        Field(pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"),
    ]
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    timeout_seconds: Annotated[int, Field(ge=1, le=3600)]
    type: Literal["job.exec"]
