# generated by datamodel-codegen:
#   filename:  execution_class.json

from __future__ import annotations

from enum import StrEnum


class ExecutionClass(StrEnum):
    """
    Lab execution class
    """

    A = "A"
    B = "B"
    C = "C"
