# generated by datamodel-codegen:
#   filename:  fault_spec.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import capability, check_spec, definition_status


class Category(StrEnum):
    configuration = "configuration"
    routing = "routing"
    connectivity = "connectivity"
    service = "service"
    performance = "performance"
    security = "security"
    code = "code"


class FaultSpec(BaseModel):
    """
    Fault module specification
    """

    model_config = ConfigDict(extra="forbid")
    category: Category
    defaults: dict[str, Any] | None = None
    description: str
    """
    Markdown text, rendered by the web app
    """
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    inject_module: Annotated[str, Field(pattern="^[a-z0-9_.]+:[a-z0-9_]+$")]
    observable_symptoms: list[ObservableSymptom]
    parameters: list[Parameter]
    requires: list[capability.Capability]
    restore_module: Annotated[str, Field(pattern="^[a-z0-9_.]+:[a-z0-9_]+$")]
    status: definition_status.DefinitionStatus
    title: Annotated[str, Field(max_length=200, min_length=1)]
    verify: Annotated[list[check_spec.CheckSpec], Field(min_length=1)]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Kind(StrEnum):
    choice = "choice"
    int_range = "int_range"
    string = "string"
    boolean = "boolean"


class ObservableSymptom(RootModel[str]):
    root: Annotated[str, Field(max_length=300, min_length=1)]


class Parameter(BaseModel):
    model_config = ConfigDict(extra="forbid")
    description: Annotated[str | None, Field(max_length=300)] = None
    kind: Kind
    name: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    values: list[str | Values | bool] | None = None


class Values(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
