# generated by datamodel-codegen:
#   filename:  fault_inject_job.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class FaultInjectJob(BaseModel):
    """
    Inject a fault
    """

    model_config = ConfigDict(extra="forbid")
    fault_id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    fault_version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """
    job_id: Annotated[
        str,
        Field(pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"),
    ]
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    parameters: dict[str, Any]
    type: Literal["job.fault.inject"]
