# generated by datamodel-codegen:
#   filename:  freshness_state.json

from __future__ import annotations

from enum import StrEnum


class FreshnessState(StrEnum):
    """
    Maintenance freshness
    """

    current = "current"
    needs_review = "needs_review"
    stale = "stale"
    broken = "broken"
    update_available = "update_available"
