# generated by datamodel-codegen:
#   filename:  grader_manifest.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import capability, check_spec, definition_status


class Check(BaseModel):
    model_config = ConfigDict(extra="forbid")
    description: Annotated[str, Field(max_length=300, min_length=1)]
    hidden: bool
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    objective_id: Annotated[
        str | None, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ] = None
    spec: check_spec.CheckSpec | None = None
    weight: Annotated[float, Field(ge=0.0)]


class GraderManifest(BaseModel):
    """
    Grader manifest
    """

    model_config = ConfigDict(extra="forbid")
    checks: Annotated[list[Check], Field(min_length=1)]
    entrypoint: Annotated[str, Field(pattern="^[a-z0-9_.]+:[a-z0-9_]+$")]
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    kind: Kind
    requires: list[capability.Capability]
    status: definition_status.DefinitionStatus
    timeout_seconds: Annotated[int, Field(ge=1, le=3600)]
    title: Annotated[str, Field(max_length=200, min_length=1)]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Kind(StrEnum):
    deterministic = "deterministic"
    test_runner = "test_runner"
