# generated by datamodel-codegen:
#   filename:  hint_tier.json

from __future__ import annotations

from enum import StrEnum


class HintTier(StrEnum):
    """
    Hint tier
    """

    none = "none"
    minor = "minor"
    strong = "strong"
    solution = "solution"
