# generated by datamodel-codegen:
#   filename:  inline_node.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class InlineNode1(BaseModel):
    """
    Lesson inline render node
    """

    model_config = ConfigDict(extra="forbid")
    kind: Literal["text"]
    value: str


class InlineNode2(BaseModel):
    """
    Lesson inline render node
    """

    model_config = ConfigDict(extra="forbid")
    kind: Literal["code"]
    value: str


class InlineNode3(BaseModel):
    """
    Lesson inline render node
    """

    model_config = ConfigDict(extra="forbid")
    kind: Literal["kbd"]
    value: str


class InlineNode4(BaseModel):
    """
    Lesson inline render node
    """

    model_config = ConfigDict(extra="forbid")
    kind: Literal["break"]


class InlineNode5(BaseModel):
    """
    Lesson inline render node
    """

    model_config = ConfigDict(extra="forbid")
    claim_id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    kind: Literal["claim_ref"]


class InlineNode6(BaseModel):
    """
    Lesson inline render node
    """

    model_config = ConfigDict(extra="forbid")
    children: list[
        InlineNode1
        | InlineNode2
        | InlineNode3
        | InlineNode4
        | InlineNode5
        | InlineNode6
        | InlineNode7
        | InlineNode8
    ]
    kind: Literal["strong"]


class InlineNode7(BaseModel):
    """
    Lesson inline render node
    """

    model_config = ConfigDict(extra="forbid")
    children: list[
        InlineNode1
        | InlineNode2
        | InlineNode3
        | InlineNode4
        | InlineNode5
        | InlineNode6
        | InlineNode7
        | InlineNode8
    ]
    kind: Literal["emphasis"]


class InlineNode8(BaseModel):
    """
    Lesson inline render node
    """

    model_config = ConfigDict(extra="forbid")
    children: list[
        InlineNode1
        | InlineNode2
        | InlineNode3
        | InlineNode4
        | InlineNode5
        | InlineNode6
        | InlineNode7
        | InlineNode8
    ]
    href: Annotated[str, Field(min_length=1)]
    kind: Literal["link"]


InlineNode6.model_rebuild()
InlineNode7.model_rebuild()
InlineNode8.model_rebuild()
