# generated by datamodel-codegen:
#   filename:  lab_status.json

from __future__ import annotations

from enum import StrEnum


class LabStatus(StrEnum):
    """
    Lab lifecycle state, RFP §86
    """

    queued = "queued"
    provisioning = "provisioning"
    baseline_check = "baseline_check"
    fault_injection = "fault_injection"
    fault_check = "fault_check"
    ready = "ready"
    active = "active"
    grading = "grading"
    completed = "completed"
    destroying = "destroying"
    destroyed = "destroyed"
    failed = "failed"
