# generated by datamodel-codegen:
#   filename:  lab_worker.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import capability


class AgentVersion(RootModel[str]):
    root: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Endpoint(RootModel[str]):
    root: Annotated[str, Field(max_length=2048, pattern="^https?:\\/\\/[^\\s/$.?#][^\\s]*$")]


class Hostname(RootModel[str]):
    root: Annotated[str, Field(max_length=253)]


class LabWorker(BaseModel):
    """
    Registered lab worker
    """

    model_config = ConfigDict(extra="forbid")
    active_sessions: Annotated[int, Field(ge=0, le=9007199254740991)]
    agent_version: AgentVersion | None
    capabilities: list[capability.Capability]
    endpoint: Endpoint | None
    hostname: Hostname | None
    id: Annotated[str, Field(max_length=120, min_length=1)]
    last_heartbeat_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    load: Load
    registered_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    runtime_versions: dict[str, str]
    status: Status


class Load(BaseModel):
    model_config = ConfigDict(extra="forbid")
    cpu_percent: Annotated[float, Field(ge=0.0, le=100.0)]
    memory_percent: Annotated[float, Field(ge=0.0, le=100.0)]


class Status(StrEnum):
    online = "online"
    degraded = "degraded"
    offline = "offline"
