# generated by datamodel-codegen:
#   filename:  lab_spec.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import capability


class AllowlistItem(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Egress(StrEnum):
    deny = "deny"
    allowlist = "allowlist"


class LabSpec(BaseModel):
    """
    Lab specification
    """

    model_config = ConfigDict(extra="forbid")
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    links: list[Link]
    network: Network
    nodes: Annotated[list[Node], Field(min_length=1)]
    requires: Annotated[list[capability.Capability], Field(min_length=1)]
    resources: Resources
    snapshot: bool
    title: Annotated[str, Field(max_length=200, min_length=1)]
    ttl_minutes: Annotated[int, Field(ge=1, le=9007199254740991)]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Link(BaseModel):
    model_config = ConfigDict(extra="forbid")
    a: Annotated[str, Field(min_length=1)]
    """
    node:interface
    """
    b: Annotated[str, Field(min_length=1)]
    """
    node:interface
    """


class Network(BaseModel):
    model_config = ConfigDict(extra="forbid")
    allowlist: list[AllowlistItem]
    egress: Egress


class Node(BaseModel):
    model_config = ConfigDict(extra="forbid")
    config: dict[str, Any] | None = None
    image: Annotated[str, Field(max_length=300, min_length=1)]
    name: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    role: Role


class Resources(BaseModel):
    model_config = ConfigDict(extra="forbid")
    cpu_millicores: Annotated[int, Field(ge=1, le=9007199254740991)]
    disk_mb: Annotated[int, Field(ge=1, le=9007199254740991)]
    memory_mb: Annotated[int, Field(ge=1, le=9007199254740991)]


class Role(StrEnum):
    host = "host"
    router = "router"
    switch = "switch"
    server = "server"
    client = "client"
    runner = "runner"
