# generated by datamodel-codegen:
#   filename:  lab_node_config.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Bgp(BaseModel):
    model_config = ConfigDict(extra="forbid")
    cluster_id: Annotated[str | None, Field(pattern="^\\d{1,3}(?:\\.\\d{1,3}){3}$")] = None
    neighbors: list[Neighbor]
    networks: list[Network]


class Daemon(StrEnum):
    bgpd = "bgpd"
    ospfd = "ospfd"
    isisd = "isisd"
    ldpd = "ldpd"
    bfdd = "bfdd"


class Interface(BaseModel):
    model_config = ConfigDict(extra="forbid")
    ipv4: Annotated[str | None, Field(pattern="^\\d{1,3}(?:\\.\\d{1,3}){3}\\/\\d{1,2}$")] = None
    name: Annotated[str, Field(max_length=15, min_length=1)]


class LabNodeConfig1(BaseModel):
    """
    Node configuration rendered by providers
    """

    model_config = ConfigDict(extra="forbid")
    hostname: Annotated[
        str | None, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ] = None
    interfaces: list[Interface]
    kind: Literal["linux"]
    routes: list[Route]
    shell: Annotated[str, Field(max_length=200, min_length=1)]


class LabNodeConfig2(BaseModel):
    """
    Node configuration rendered by providers
    """

    model_config = ConfigDict(extra="forbid")
    asn: Annotated[int, Field(ge=1, le=4294967295)]
    bgp: Bgp
    daemons: list[Daemon]
    hostname: Annotated[
        str | None, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ] = None
    interfaces: list[Interface]
    kind: Literal["frr"]
    loopback: Loopback | None = None
    router_id: Annotated[str, Field(pattern="^\\d{1,3}(?:\\.\\d{1,3}){3}$")]
    shell: Annotated[str, Field(max_length=200, min_length=1)]


class LabNodeConfig(RootModel[LabNodeConfig1 | LabNodeConfig2]):
    root: Annotated[LabNodeConfig1 | LabNodeConfig2, Field(title="LabNodeConfig")]
    """
    Node configuration rendered by providers
    """


class Loopback(BaseModel):
    model_config = ConfigDict(extra="forbid")
    ipv4: Annotated[str | None, Field(pattern="^\\d{1,3}(?:\\.\\d{1,3}){3}\\/\\d{1,2}$")] = None
    name: Annotated[str, Field(max_length=15, min_length=1)]


class Neighbor(BaseModel):
    model_config = ConfigDict(extra="forbid")
    address: Annotated[str, Field(pattern="^\\d{1,3}(?:\\.\\d{1,3}){3}$")]
    description: Annotated[str | None, Field(max_length=80)] = None
    remote_asn: Annotated[int, Field(ge=1, le=4294967295)]
    route_reflector_client: bool | None = None


class Network(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Route(BaseModel):
    model_config = ConfigDict(extra="forbid")
    prefix: Annotated[str, Field(min_length=1)]
    via: Annotated[str, Field(pattern="^\\d{1,3}(?:\\.\\d{1,3}){3}$")]
