# generated by datamodel-codegen:
#   filename:  lab_provider_descriptor.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import capability


class Kind(StrEnum):
    echo = "echo"
    sandbox = "sandbox"
    lab_worker = "lab_worker"


class LabProviderDescriptor(BaseModel):
    """
    Provider descriptor
    """

    model_config = ConfigDict(extra="forbid")
    capabilities: list[capability.Capability]
    endpoint: Annotated[
        str | None, Field(max_length=2048, pattern="^https?:\\/\\/[^\\s/$.?#][^\\s]*$")
    ] = None
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    kind: Kind
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """
