# generated by datamodel-codegen:
#   filename:  learner.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import execution_mode


class AiExecution(BaseModel):
    model_config = ConfigDict(extra="forbid")
    coach: execution_mode.ExecutionMode
    interview: execution_mode.ExecutionMode
    review: execution_mode.ExecutionMode
    tutor: execution_mode.ExecutionMode


class Identity(BaseModel):
    model_config = ConfigDict(extra="forbid")
    email: Annotated[str, Field(max_length=254, pattern="^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")]
    provider: Literal["cloudflare_access"]
    subject: Annotated[str | None, Field(min_length=1)] = None


class Learner(BaseModel):
    """
    Learner record
    """

    model_config = ConfigDict(extra="forbid")
    created_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    display_name: Annotated[str, Field(max_length=120, min_length=1)]
    id: Annotated[str, Field(pattern="^HM-LRN-\\d{6}$")]
    identity: Identity
    settings: Settings
    updated_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """


class Settings(BaseModel):
    model_config = ConfigDict(extra="forbid")
    ai_execution: AiExecution
    shortcuts: dict[str, str] | None = None
    timezone: Annotated[str | None, Field(min_length=1)] = None
