# generated by datamodel-codegen:
#   filename:  lesson_element.json

from __future__ import annotations

from enum import StrEnum


class LessonElement(StrEnum):
    """
    RFP §110 lesson element
    """

    motivation = "motivation"
    mental_model = "mental_model"
    explanation = "explanation"
    diagram = "diagram"
    worked_example = "worked_example"
    misconception = "misconception"
    prediction = "prediction"
    guided_exercise = "guided_exercise"
    demonstration = "demonstration"
    independent_problem = "independent_problem"
    reflection = "reflection"
    mastery_evaluation = "mastery_evaluation"
