# generated by datamodel-codegen:
#   filename:  lesson.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import claim, lesson_section, product_mode, question
from . import qa_state as qa_state_1


class EstimatedMinutes(BaseModel):
    model_config = ConfigDict(extra="forbid")
    guided_lab: Annotated[int, Field(ge=0, le=9007199254740991)]
    independent_practice: Annotated[int, Field(ge=0, le=9007199254740991)]
    instruction: Annotated[int, Field(ge=0, le=9007199254740991)]
    total: Annotated[int, Field(ge=1, le=9007199254740991)]


class GraderConstraints(BaseModel):
    model_config = ConfigDict(extra="forbid")
    preserve: list[PreserveItem]
    reject: list[RejectItem]
    required: Annotated[list[RequiredItem], Field(min_length=1)]


class Lab(BaseModel):
    model_config = ConfigDict(extra="forbid")
    grader_constraints: GraderConstraints | None = None
    mode: product_mode.ProductMode
    problem_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    title: Annotated[str, Field(max_length=200, min_length=1)]


class Lesson(BaseModel):
    """
    Compiled lesson
    """

    model_config = ConfigDict(extra="forbid")
    body_hash: Annotated[str, Field(pattern="^[a-f0-9]{64}$")]
    claims: list[claim.Claim]
    course_id: Annotated[str, Field(pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    """
    Course id slug, e.g. linux-networking
    """
    difficulty: Annotated[int, Field(ge=1, le=5)]
    estimated_minutes: EstimatedMinutes
    id: Annotated[str, Field(pattern="^HM-LESSON-[a-z0-9-]+-\\d{2}$")]
    labs: list[Lab]
    module_id: Annotated[str, Field(pattern="^[a-z0-9-]+\\.[a-z0-9-]+$")]
    """
    Module id <course>.<slug>, e.g. linux-networking.routing
    """
    objectives: Annotated[list[Objective], Field(min_length=1)]
    order: Annotated[int, Field(ge=1, le=9007199254740991)]
    prerequisite_lesson_ids: list[PrerequisiteLessonId]
    qa_state: qa_state_1.QaState
    questions: list[question.Question]
    review: Review
    sections: list[lesson_section.LessonSection]
    skill_ids: Annotated[list[SkillId], Field(min_length=1)]
    slug: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    source_ids: list[SourceId]
    source_path: Annotated[str | None, Field(min_length=1)] = None
    summary: Annotated[str, Field(max_length=600, min_length=1)]
    title: Annotated[str, Field(max_length=200, min_length=1)]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Objective(BaseModel):
    model_config = ConfigDict(extra="forbid")
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    skill_ids: Annotated[list[SkillId], Field(min_length=1)]
    text: Annotated[str, Field(max_length=300, min_length=1)]


class PrerequisiteLessonId(RootModel[str]):
    root: Annotated[str, Field(pattern="^HM-LESSON-[a-z0-9-]+-\\d{2}$")]


class PreserveItem(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class RejectItem(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class RequiredItem(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class Review(BaseModel):
    model_config = ConfigDict(extra="forbid")
    approved_at: Annotated[
        str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ] = None
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    approved_by: Annotated[str | None, Field(max_length=120)] = None
    execution_tested_at: Annotated[
        str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ] = None
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    instructional_reviewed_at: Annotated[
        str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ] = None
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    instructional_reviewed_by: Annotated[str | None, Field(max_length=120)] = None
    notes: str | None = None
    """
    Markdown text, rendered by the web app
    """
    technical_reviewed_at: Annotated[
        str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ] = None
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    technical_reviewed_by: Annotated[str | None, Field(max_length=120)] = None


class SkillId(RootModel[str]):
    root: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """


class SourceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    """
    Source id, e.g. src.iproute2.ip-route
    """


Lesson.model_rebuild()
