# generated by datamodel-codegen:
#   filename:  lesson_section.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import block_node, lesson_element


class LessonSection(BaseModel):
    """
    Lesson section tagged with its §110 element
    """

    model_config = ConfigDict(extra="forbid")
    blocks: list[
        block_node.BlockNode1
        | block_node.BlockNode2
        | block_node.BlockNode3
        | block_node.BlockNode4
        | block_node.BlockNode5
        | block_node.BlockNode6
        | block_node.BlockNode7
        | block_node.BlockNode8
        | block_node.BlockNode9
        | block_node.BlockNode10
    ]
    element: lesson_element.LessonElement
    heading: Annotated[str, Field(max_length=200, min_length=1)]
