# generated by datamodel-codegen:
#   filename:  log_event.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Level(StrEnum):
    debug = "debug"
    info = "info"
    warn = "warn"
    error = "error"


class LogEvent(BaseModel):
    """
    Log line event
    """

    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    level: Level
    message: Annotated[str, Field(max_length=4000)]
    type: Literal["event.log"]
