# generated by datamodel-codegen:
#   filename:  mastery_update.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import confidence as confidence_1


class EvidenceId(RootModel[str]):
    root: Annotated[str, Field(pattern="^HM-EV-\\d{6,}$")]


class MasteryUpdate(BaseModel):
    """
    Versioned mastery update
    """

    model_config = ConfigDict(extra="forbid")
    algorithm_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    algorithm_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    confidence: confidence_1.Confidence
    created_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    evidence_count: Annotated[int, Field(ge=0, le=9007199254740991)]
    evidence_ids: list[EvidenceId]
    learner_id: Annotated[str, Field(pattern="^HM-LRN-\\d{6}$")]
    mastery_after: Annotated[float, Field(ge=0.0, le=1.0)]
    mastery_before: Annotated[float, Field(ge=0.0, le=1.0)]
    skill_id: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
    skill_version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """
