# generated by datamodel-codegen:
#   filename:  module.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class LessonId(RootModel[str]):
    root: Annotated[str, Field(pattern="^HM-LESSON-[a-z0-9-]+-\\d{2}$")]


class Module(BaseModel):
    """
    Course module
    """

    model_config = ConfigDict(extra="forbid")
    course_id: Annotated[str, Field(pattern="^[a-z0-9]+(?:-[a-z0-9]+)*$")]
    """
    Course id slug, e.g. linux-networking
    """
    id: Annotated[str, Field(pattern="^[a-z0-9-]+\\.[a-z0-9-]+$")]
    """
    Module id <course>.<slug>, e.g. linux-networking.routing
    """
    lesson_ids: list[LessonId]
    order: Annotated[int, Field(ge=1, le=9007199254740991)]
    skill_ids: list[SkillId]
    source_path: Annotated[str | None, Field(min_length=1)] = None
    summary: Annotated[str, Field(max_length=600, min_length=1)]
    title: Annotated[str, Field(max_length=200, min_length=1)]


class SkillId(RootModel[str]):
    root: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
