# generated by datamodel-codegen:
#   filename:  problem_instance.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class FaultVersion(BaseModel):
    model_config = ConfigDict(extra="forbid")
    fault_id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class ProblemInstance(BaseModel):
    """
    Seeded problem instance
    """

    model_config = ConfigDict(extra="forbid")
    created_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    fault_versions: list[FaultVersion]
    grader_version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """
    id: Annotated[str, Field(pattern="^HM-PI-\\d{6,}$")]
    lab_spec_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    parameters: dict[str, Any]
    problem_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    problem_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    reference_solution_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
    spec_hash: Annotated[str, Field(pattern="^[a-f0-9]{64}$")]
    validation: Validation
    validation_steps: list[ValidationStep]


class Step(StrEnum):
    schema_validation = "schema_validation"
    provision_baseline = "provision_baseline"
    validate_baseline = "validate_baseline"
    inject_fault = "inject_fault"
    verify_failure = "verify_failure"
    execute_reference_solution = "execute_reference_solution"
    run_graders = "run_graders"
    restore_scenario = "restore_scenario"


class Validation(StrEnum):
    pending = "pending"
    validated = "validated"
    rejected = "rejected"


class ValidationStep(BaseModel):
    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    detail: Annotated[str | None, Field(max_length=1000)] = None
    passed: bool
    step: Step
