# generated by datamodel-codegen:
#   filename:  problem_spec.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import capability, definition_status, product_mode
from . import qa_state as qa_state_1


class CheckId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]


class Fault(BaseModel):
    model_config = ConfigDict(extra="forbid")
    fault_id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    parameters: dict[str, Any] | None = None
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Hint(BaseModel):
    model_config = ConfigDict(extra="forbid")
    mastery_cap_percent: Annotated[int, Field(ge=0, le=100)]
    text: str
    """
    Markdown text, rendered by the web app
    """
    tier: Tier


class Kind(StrEnum):
    choice = "choice"
    int_range = "int_range"
    string = "string"
    boolean = "boolean"


class Objective(BaseModel):
    model_config = ConfigDict(extra="forbid")
    check_ids: list[CheckId]
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    skill_id: Annotated[
        str | None, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ] = None
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
    text: Annotated[str, Field(max_length=300, min_length=1)]


class ProblemSpec(BaseModel):
    """
    Problem archetype
    """

    model_config = ConfigDict(extra="forbid")
    difficulty: Annotated[int, Field(ge=1, le=5)]
    domain: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    faults: list[Fault]
    grader_id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    grader_version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """
    hints: list[Hint]
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    lab_spec_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    lab_spec_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    modes: Annotated[list[product_mode.ProductMode], Field(min_length=1)]
    objectives: Annotated[list[Objective], Field(min_length=1)]
    qa_state: qa_state_1.QaState
    reference_solution: Annotated[str, Field(pattern="^[a-z0-9_.]+:[a-z0-9_]+$")]
    reference_solution_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    requires: Annotated[list[capability.Capability], Field(min_length=1)]
    scenario: str
    """
    Markdown text, rendered by the web app
    """
    skill_ids: Annotated[list[SkillId], Field(min_length=1)]
    status: definition_status.DefinitionStatus
    summary: Annotated[str, Field(max_length=600, min_length=1)]
    time_limit_minutes: Annotated[int | None, Field(ge=1, le=9007199254740991)] = None
    title: Annotated[str, Field(max_length=200, min_length=1)]
    variation: list[VariationItem]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class SkillId(RootModel[str]):
    root: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """


class Tier(StrEnum):
    minor = "minor"
    strong = "strong"
    solution = "solution"


class Values(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class VariationItem(BaseModel):
    model_config = ConfigDict(extra="forbid")
    description: Annotated[str | None, Field(max_length=300)] = None
    kind: Kind
    name: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    values: list[str | Values | bool] | None = None
