# generated by datamodel-codegen:
#   filename:  product_mode.json

from __future__ import annotations

from enum import StrEnum


class ProductMode(StrEnum):
    """
    Product mode, RFP §3
    """

    learn = "learn"
    guided_lab = "guided_lab"
    practice = "practice"
    challenge = "challenge"
    blind_incident = "blind_incident"
    interview = "interview"
    project = "project"
