# generated by datamodel-codegen:
#   filename:  provision_request.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import lab_spec as lab_spec_1


class ProvisionRequest(BaseModel):
    """
    Provision request
    """

    model_config = ConfigDict(extra="forbid")
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    lab_spec: lab_spec_1.LabSpec
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
