# generated by datamodel-codegen:
#   filename:  provider_health.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class ProviderHealth(BaseModel):
    """
    Provider health
    """

    model_config = ConfigDict(extra="forbid")
    active_sessions: Annotated[int, Field(ge=0, le=9007199254740991)]
    checked_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    detail: Annotated[str | None, Field(max_length=500)] = None
    ok: bool
    provider_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
