# generated by datamodel-codegen:
#   filename:  provision_job.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import lab_spec as lab_spec_1
from . import problem_instance as problem_instance_1


class ProvisionJob(BaseModel):
    """
    Provision a lab
    """

    model_config = ConfigDict(extra="forbid")
    job_id: Annotated[
        str,
        Field(pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"),
    ]
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    lab_spec: lab_spec_1.LabSpec
    problem_instance: problem_instance_1.ProblemInstance | None = None
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
    type: Literal["job.provision"]
