# generated by datamodel-codegen:
#   filename:  pty_control_message.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Code(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class PtyControlMessage1(BaseModel):
    """
    PTY control frame
    """

    model_config = ConfigDict(extra="forbid")
    cols: Annotated[int, Field(ge=1, le=9007199254740991)]
    rows: Annotated[int, Field(ge=1, le=9007199254740991)]
    type: Literal["resize"]


class PtyControlMessage2(BaseModel):
    """
    PTY control frame
    """

    model_config = ConfigDict(extra="forbid")
    type: Literal["ready"]


class PtyControlMessage3(BaseModel):
    """
    PTY control frame
    """

    model_config = ConfigDict(extra="forbid")
    code: Code | None
    signal: Signal | None = None
    type: Literal["exit"]


class PtyControlMessage4(BaseModel):
    """
    PTY control frame
    """

    model_config = ConfigDict(extra="forbid")
    message: Annotated[str, Field(max_length=1000)]
    type: Literal["error"]


class PtyControlMessage(
    RootModel[PtyControlMessage1 | PtyControlMessage2 | PtyControlMessage3 | PtyControlMessage4]
):
    root: Annotated[
        PtyControlMessage1 | PtyControlMessage2 | PtyControlMessage3 | PtyControlMessage4,
        Field(title="PtyControlMessage"),
    ]
    """
    PTY control frame
    """


class Signal(RootModel[str]):
    root: Annotated[str, Field(max_length=20)]
