# generated by datamodel-codegen:
#   filename:  qa_state.json

from __future__ import annotations

from enum import StrEnum


class QaState(StrEnum):
    """
    Content QA state
    """

    draft = "draft"
    technical_review = "technical_review"
    instructional_review = "instructional_review"
    execution_test = "execution_test"
    approved = "approved"
    published = "published"
    deprecated = "deprecated"
    archived = "archived"
