# generated by datamodel-codegen:
#   filename:  question.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Kind(StrEnum):
    prediction = "prediction"
    knowledge_check = "knowledge_check"
    reflection = "reflection"
    mastery = "mastery"


class Option(BaseModel):
    model_config = ConfigDict(extra="forbid")
    correct: bool
    feedback: str | None = None
    """
    Markdown text, rendered by the web app
    """
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    text: str
    """
    Markdown text, rendered by the web app
    """


class Question(BaseModel):
    """
    Lesson question
    """

    model_config = ConfigDict(extra="forbid")
    answer: str | None = None
    """
    Markdown text, rendered by the web app
    """
    difficulty: Annotated[int, Field(ge=1, le=5)]
    explanation: str
    """
    Markdown text, rendered by the web app
    """
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    kind: Kind
    lesson_id: Annotated[str, Field(pattern="^HM-LESSON-[a-z0-9-]+-\\d{2}$")]
    options: Annotated[list[Option] | None, Field(min_length=2)] = None
    prompt: str
    """
    Markdown text, rendered by the web app
    """
    skill_ids: list[SkillId]


class SkillId(RootModel[str]):
    root: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
