# generated by datamodel-codegen:
#   filename:  readiness_snapshot.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import confidence as confidence_1


class Gate(BaseModel):
    model_config = ConfigDict(extra="forbid")
    blocking: bool
    competency_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    satisfied: bool
    score_percent: Annotated[int | None, Field(ge=0, le=100)] = None


class ReadinessSnapshot(BaseModel):
    """
    Readiness with confidence and gates
    """

    model_config = ConfigDict(extra="forbid")
    algorithm_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    algorithm_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    computed_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    confidence: confidence_1.Confidence
    evidence_count: Annotated[int, Field(ge=0, le=9007199254740991)]
    gates: list[Gate]
    last_tested_at: Annotated[
        str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ] = None
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    learner_id: Annotated[str, Field(pattern="^HM-LRN-\\d{6}$")]
    role_profile_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    role_profile_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    score_percent: Annotated[int, Field(ge=0, le=100)]
