# generated by datamodel-codegen:
#   filename:  reconcile_event.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Node(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]


class ReconcileEvent(BaseModel):
    """
    Worker reconciliation report
    """

    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    sessions: list[Session]
    type: Literal["event.reconcile"]
    worker_id: Annotated[str, Field(max_length=120, min_length=1)]


class Session(BaseModel):
    model_config = ConfigDict(extra="forbid")
    handle: Annotated[str, Field(min_length=1)]
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    nodes: list[Node]
