# generated by datamodel-codegen:
#   filename:  recording_header.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class Env(BaseModel):
    model_config = ConfigDict(extra="forbid")
    SHELL: str
    TERM: str


class Hivemind(BaseModel):
    model_config = ConfigDict(extra="forbid")
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    provider_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    recorded_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    redaction_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """


class RecordingHeader(BaseModel):
    """
    asciicast v2 recording header
    """

    model_config = ConfigDict(extra="forbid")
    env: Env
    height: Annotated[int, Field(ge=1, le=9007199254740991)]
    hivemind: Hivemind
    timestamp: Annotated[int, Field(ge=0, le=9007199254740991)]
    title: Annotated[str, Field(max_length=200)]
    version: Literal[2]
    width: Annotated[int, Field(ge=1, le=9007199254740991)]
