# generated by datamodel-codegen:
#   filename:  reconcile_expected.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import lab_status


class ReconcileExpected(BaseModel):
    """
    Sessions expected on a worker
    """

    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    sessions: list[Session]
    type: Literal["reconcile.expected"]
    worker_id: Annotated[str, Field(max_length=120, min_length=1)]


class Session(BaseModel):
    model_config = ConfigDict(extra="forbid")
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    status: lab_status.LabStatus
