# generated by datamodel-codegen:
#   filename:  review_item.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import qa_state as qa_state_1


class Kind(StrEnum):
    lesson = "lesson"
    claim = "claim"
    problem = "problem"
    source = "source"
    work_order = "work_order"


class Resolution(StrEnum):
    approved = "approved"
    rejected = "rejected"
    changes_requested = "changes_requested"


class ReviewItem(BaseModel):
    """
    Review queue item
    """

    model_config = ConfigDict(extra="forbid")
    id: Annotated[str, Field(pattern="^HM-RVW-\\d{4,}$")]
    kind: Kind
    notes: str | None = None
    """
    Markdown text, rendered by the web app
    """
    opened_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    qa_state: qa_state_1.QaState
    resolution: Resolution | None = None
    resolved_at: Annotated[
        str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ] = None
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    reviewer: Annotated[str | None, Field(max_length=120)] = None
    target_id: Annotated[str, Field(min_length=1)]
    work_order_id: Annotated[str | None, Field(pattern="^HM-WO-\\d{4,}$")] = None
