# generated by datamodel-codegen:
#   filename:  role_profile.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import definition_status


class Competency(BaseModel):
    model_config = ConfigDict(extra="forbid")
    competency_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]
    min_readiness: Annotated[float | None, Field(ge=0.0, le=1.0)] = None
    required: bool
    weight: Annotated[float, Field(ge=0.0, le=1.0)]


class RoleProfile(BaseModel):
    """
    Role profile
    """

    model_config = ConfigDict(extra="forbid")
    company: Annotated[str | None, Field(max_length=120)] = None
    competencies: Annotated[list[Competency], Field(min_length=1)]
    family: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    """
    Role family, e.g. network-infrastructure
    """
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    level: Annotated[str, Field(max_length=60, min_length=1)]
    source_ids: list[SourceId]
    status: definition_status.DefinitionStatus
    summary: str
    """
    Markdown text, rendered by the web app
    """
    title: Annotated[str, Field(max_length=200, min_length=1)]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class SourceId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    """
    Source id, e.g. src.iproute2.ip-route
    """
