# generated by datamodel-codegen:
#   filename:  sequenced_session_event.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import session_event


class SequencedSessionEvent(BaseModel):
    """
    Session event with sequence and revision
    """

    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    event: Annotated[
        session_event.SessionEvent1
        | session_event.SessionEvent2
        | session_event.SessionEvent3
        | session_event.SessionEvent4,
        Field(title="SessionEvent"),
    ]
    """
    Sequenced session event payload
    """
    revision: Annotated[int, Field(ge=0, le=9007199254740991)]
    sequence: Annotated[int, Field(ge=0, le=9007199254740991)]
