# generated by datamodel-codegen:
#   filename:  session_client_message.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SessionClientMessage1(BaseModel):
    """
    Client → session Worker WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    protocol_version: Literal[2]
    size: Size
    type: Literal["pty_open"]


class SessionClientMessage2(BaseModel):
    """
    Client → session Worker WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    data: Annotated[str, Field(max_length=16384, min_length=1)]
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    protocol_version: Literal[2]
    type: Literal["pty_input"]


class SessionClientMessage3(BaseModel):
    """
    Client → session Worker WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    protocol_version: Literal[2]
    size: Size
    type: Literal["pty_resize"]


class SessionClientMessage4(BaseModel):
    """
    Client → session Worker WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    latest_sequence: Annotated[int, Field(ge=0, le=9007199254740991)]
    protocol_version: Literal[2]
    type: Literal["resync"]


class SessionClientMessage(
    RootModel[
        SessionClientMessage1
        | SessionClientMessage2
        | SessionClientMessage3
        | SessionClientMessage4
    ]
):
    root: Annotated[
        SessionClientMessage1
        | SessionClientMessage2
        | SessionClientMessage3
        | SessionClientMessage4,
        Field(title="SessionClientMessage"),
    ]
    """
    Client → session Worker WebSocket message
    """


class Size(BaseModel):
    model_config = ConfigDict(extra="forbid")
    cols: Annotated[int, Field(ge=1, le=500)]
    rows: Annotated[int, Field(ge=1, le=200)]
