# generated by datamodel-codegen:
#   filename:  session_server_message.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import sequenced_session_event, session_event, session_summary


class Code(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class Code2(StrEnum):
    malformed = "malformed"
    not_owner = "not_owner"
    not_ready = "not_ready"
    unknown_node = "unknown_node"
    pty_unavailable = "pty_unavailable"
    rate_limited = "rate_limited"
    resync_required = "resync_required"
    session_finished = "session_finished"


class Reason(StrEnum):
    malformed = "malformed"
    not_owner = "not_owner"
    not_ready = "not_ready"
    unknown_node = "unknown_node"
    pty_unavailable = "pty_unavailable"
    rate_limited = "rate_limited"
    resync_required = "resync_required"
    session_finished = "session_finished"


class SessionServerMessage1(BaseModel):
    """
    Session Worker → client WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    connection_id: Annotated[
        str,
        Field(pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"),
    ]
    protocol_version: Literal[2]
    server_time: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    type: Literal["welcome"]


class SessionServerMessage2(BaseModel):
    """
    Session Worker → client WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    latest_sequence: Annotated[int, Field(ge=0, le=9007199254740991)]
    protocol_version: Literal[2]
    recent_events: list[sequenced_session_event.SequencedSessionEvent]
    server_time: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    session: session_summary.SessionSummary
    type: Literal["snapshot"]


class SessionServerMessage3(BaseModel):
    """
    Session Worker → client WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    event: Annotated[
        session_event.SessionEvent1
        | session_event.SessionEvent2
        | session_event.SessionEvent3
        | session_event.SessionEvent4,
        Field(title="SessionEvent"),
    ]
    """
    Sequenced session event payload
    """
    protocol_version: Literal[2]
    revision: Annotated[int, Field(ge=0, le=9007199254740991)]
    sequence: Annotated[int, Field(ge=0, le=9007199254740991)]
    type: Literal["event"]


class SessionServerMessage4(BaseModel):
    """
    Session Worker → client WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    data: Annotated[str, Field(max_length=16384, min_length=1)]
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    protocol_version: Literal[2]
    type: Literal["pty_output"]


class SessionServerMessage5(BaseModel):
    """
    Session Worker → client WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    protocol_version: Literal[2]
    type: Literal["pty_ready"]


class SessionServerMessage6(BaseModel):
    """
    Session Worker → client WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    code: Code | None
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    protocol_version: Literal[2]
    type: Literal["pty_exit"]


class SessionServerMessage7(BaseModel):
    """
    Session Worker → client WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    code: Code2
    detail: Annotated[str | None, Field(max_length=500)] = None
    protocol_version: Literal[2]
    revision: Annotated[int, Field(ge=0, le=9007199254740991)]
    type: Literal["rejected"]


class SessionServerMessage8(BaseModel):
    """
    Session Worker → client WebSocket message
    """

    model_config = ConfigDict(extra="forbid")
    protocol_version: Literal[2]
    reason: Reason
    revision: Annotated[int, Field(ge=0, le=9007199254740991)]
    type: Literal["resync_required"]


class SessionServerMessage(
    RootModel[
        SessionServerMessage1
        | SessionServerMessage2
        | SessionServerMessage3
        | SessionServerMessage4
        | SessionServerMessage5
        | SessionServerMessage6
        | SessionServerMessage7
        | SessionServerMessage8
    ]
):
    root: Annotated[
        SessionServerMessage1
        | SessionServerMessage2
        | SessionServerMessage3
        | SessionServerMessage4
        | SessionServerMessage5
        | SessionServerMessage6
        | SessionServerMessage7
        | SessionServerMessage8,
        Field(title="SessionServerMessage"),
    ]
    """
    Session Worker → client WebSocket message
    """
