# generated by datamodel-codegen:
#   filename:  session_summary.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import capability, execution_class, lab_status


class ExpiresAt(RootModel[str]):
    root: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """


class HardTtlAt(RootModel[str]):
    root: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """


class Node(BaseModel):
    model_config = ConfigDict(extra="forbid")
    address: Annotated[str | None, Field(min_length=1)] = None
    name: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    role: Role


class ProviderId(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]


class Reason(RootModel[str]):
    root: Annotated[str, Field(max_length=500)]


class RecordingKey(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Role(StrEnum):
    host = "host"
    router = "router"
    switch = "switch"
    server = "server"
    client = "client"
    runner = "runner"


class SessionSummary(BaseModel):
    """
    Lab session summary
    """

    model_config = ConfigDict(extra="forbid")
    archetype: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    archetype_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    created_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    expires_at: ExpiresAt | None
    hard_ttl_at: HardTtlAt | None
    id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    learner_id: Annotated[str, Field(pattern="^HM-LRN-\\d{6}$")]
    nodes: list[Node]
    parameters: dict[str, Any]
    provider_class: execution_class.ExecutionClass | None
    provider_id: ProviderId | None
    reason: Reason | None
    recording_key: RecordingKey | None
    requires: Annotated[list[capability.Capability], Field(min_length=1)]
    revision: Annotated[int, Field(ge=0, le=9007199254740991)]
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
    status: lab_status.LabStatus
    updated_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    worker_id: WorkerId | None


class WorkerId(RootModel[str]):
    root: Annotated[str, Field(max_length=120, min_length=1)]
