# generated by datamodel-codegen:
#   filename:  session_event.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import lab_status


class Level(StrEnum):
    debug = "debug"
    info = "info"
    warn = "warn"
    error = "error"


class SessionEvent1(BaseModel):
    """
    Sequenced session event payload
    """

    model_config = ConfigDict(extra="forbid")
    from_: Annotated[lab_status.LabStatus, Field(alias="from")]
    reason: Annotated[str | None, Field(max_length=500)] = None
    to: lab_status.LabStatus
    type: Literal["status_changed"]


class SessionEvent2(BaseModel):
    """
    Sequenced session event payload
    """

    model_config = ConfigDict(extra="forbid")
    data: Annotated[str, Field(max_length=16384, min_length=1)]
    node: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    type: Literal["pty_output"]


class SessionEvent3(BaseModel):
    """
    Sequenced session event payload
    """

    model_config = ConfigDict(extra="forbid")
    text: Annotated[str, Field(max_length=500, min_length=1)]
    type: Literal["notice"]


class SessionEvent4(BaseModel):
    """
    Sequenced session event payload
    """

    model_config = ConfigDict(extra="forbid")
    level: Level
    message: Annotated[str, Field(max_length=4000)]
    type: Literal["log"]
