# generated by datamodel-codegen:
#   filename:  skill_definition.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import definition_status


class EvidenceMode(StrEnum):
    learn = "learn"
    guided_lab = "guided_lab"
    practice = "practice"
    challenge = "challenge"
    blind_incident = "blind_incident"
    interview = "interview"
    project = "project"


class Prerequisite(RootModel[str]):
    root: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """


class RelatedItem(RootModel[str]):
    root: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """


class SkillDefinition(BaseModel):
    """
    Versioned skill
    """

    model_config = ConfigDict(extra="forbid")
    blind_assessable: bool
    description: str
    """
    Markdown text, rendered by the web app
    """
    domain: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    """
    Top-level domain slug, e.g. linux, networking, python
    """
    evidence_modes: list[EvidenceMode]
    id: Annotated[str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
    name: Annotated[str, Field(max_length=120, min_length=1)]
    prerequisites: list[Prerequisite]
    related: list[RelatedItem]
    status: definition_status.DefinitionStatus
    tags: list[Tag]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Tag(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
