# generated by datamodel-codegen:
#   filename:  skill_graph.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Edge(BaseModel):
    model_config = ConfigDict(extra="forbid")
    from_: Annotated[
        str,
        Field(alias="from", max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$"),
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
    kind: Kind
    to: Annotated[str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """


class Kind(StrEnum):
    prerequisite = "prerequisite"
    related = "related"
    supersedes = "supersedes"
    part_of = "part_of"


class Skill(BaseModel):
    model_config = ConfigDict(extra="forbid")
    skill_id: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    """
    Skill id: domain.area.skill, e.g. linux.networking.routing_table
    """
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class SkillGraph(BaseModel):
    """
    Skill graph
    """

    model_config = ConfigDict(extra="forbid")
    edges: list[Edge]
    skills: list[Skill]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """
