# generated by datamodel-codegen:
#   filename:  source_record.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

from . import trust_tier as trust_tier_1


class Kind(StrEnum):
    rfc = "rfc"
    standard = "standard"
    official_documentation = "official_documentation"
    vendor_documentation = "vendor_documentation"
    manual_page = "manual_page"
    certification_objectives = "certification_objectives"
    free_material = "free_material"
    own_notes = "own_notes"
    book_notes = "book_notes"


class SourceRecord(BaseModel):
    """
    Source with provenance and trust
    """

    model_config = ConfigDict(extra="forbid")
    citation: Annotated[str | None, Field(max_length=500)] = None
    document_version: Annotated[str | None, Field(max_length=80)] = None
    id: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    """
    Source id, e.g. src.iproute2.ip-route
    """
    ingested: bool
    kind: Kind
    license_note: Annotated[str | None, Field(max_length=500)] = None
    notes: str | None = None
    """
    Markdown text, rendered by the web app
    """
    retrieved_at: Annotated[str | None, Field(pattern="^\\d{4}-\\d{2}-\\d{2}$")] = None
    title: Annotated[str, Field(max_length=200, min_length=1)]
    trust_tier: trust_tier_1.TrustTier
    url: Annotated[
        str | None, Field(max_length=2048, pattern="^https?:\\/\\/[^\\s/$.?#][^\\s]*$")
    ] = None
