# generated by datamodel-codegen:
#   filename:  status_event.json

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import lab_status


class StatusEvent(BaseModel):
    """
    Lifecycle status event
    """

    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    detail: Annotated[str | None, Field(max_length=500)] = None
    lab_session_id: Annotated[str, Field(pattern="^HM-LAB-\\d{6}$")]
    status: lab_status.LabStatus
    type: Literal["event.status"]
