# generated by datamodel-codegen:
#   filename:  topology_instance.json

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field

from . import lab_spec as lab_spec_1


class TopologyInstance(BaseModel):
    """
    Seeded topology instance
    """

    model_config = ConfigDict(extra="forbid")
    archetype_id: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]
    archetype_version: Annotated[
        str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")
    ]
    """
    Semantic version major.minor.patch
    """
    generator: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    lab_spec: lab_spec_1.LabSpec
    parameters: dict[str, Any]
    seed: Annotated[int, Field(ge=0, le=9007199254740991)]
    spec_hash: Annotated[str, Field(pattern="^[a-f0-9]{64}$")]
