# generated by datamodel-codegen:
#   filename:  topology_archetype.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr
from typing_extensions import TypeAliasType

from . import capability, definition_status


class Alias(RootModel[str]):
    root: Annotated[
        str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")
    ]


class AllowlistItem(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Egress(StrEnum):
    deny = "deny"
    allowlist = "allowlist"


ImagesAdditionalProperty = TypeAliasType(
    "ImagesAdditionalProperty", Annotated[str, Field(max_length=300, min_length=1)]
)


class Kind(StrEnum):
    choice = "choice"
    int_range = "int_range"
    string = "string"
    boolean = "boolean"


class Network(BaseModel):
    model_config = ConfigDict(extra="forbid")
    allowlist: list[AllowlistItem]
    egress: Egress


class Parameter(BaseModel):
    model_config = ConfigDict(extra="forbid")
    description: Annotated[str | None, Field(max_length=300)] = None
    kind: Kind
    name: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    values: list[str | Values | bool] | None = None


class Resources(BaseModel):
    model_config = ConfigDict(extra="forbid")
    cpu_millicores: Annotated[int, Field(ge=1, le=9007199254740991)]
    disk_mb: Annotated[int, Field(ge=1, le=9007199254740991)]
    memory_mb: Annotated[int, Field(ge=1, le=9007199254740991)]


class TopologyArchetype(BaseModel):
    """
    Topology archetype
    """

    model_config = ConfigDict(extra="forbid")
    aliases: list[Alias]
    description: Annotated[str, Field(max_length=600, min_length=1)]
    generator: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    id: Annotated[str, Field(max_length=96, min_length=3, pattern="^[a-z0-9_]+(?:\\.[a-z0-9_]+)+$")]
    images: dict[constr(min_length=1), ImagesAdditionalProperty]
    network: Network
    options: dict[str, Any] | None = None
    parameters: list[Parameter]
    requires: Annotated[list[capability.Capability], Field(min_length=1)]
    resources: Resources
    snapshot: bool
    status: definition_status.DefinitionStatus
    title: Annotated[str, Field(max_length=200, min_length=1)]
    ttl_minutes: Annotated[int, Field(ge=1, le=9007199254740991)]
    version: Annotated[str, Field(pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$")]
    """
    Semantic version major.minor.patch
    """


class Values(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
