# generated by datamodel-codegen:
#   filename:  trust_tier.json

from __future__ import annotations

from enum import StrEnum


class TrustTier(StrEnum):
    """
    Source trust tier
    """

    official = "official"
    vendor = "vendor"
    secondary = "secondary"
    internal = "internal"
