# generated by datamodel-codegen:
#   filename:  work_order_status.json

from __future__ import annotations

from enum import StrEnum


class WorkOrderStatus(StrEnum):
    """
    Work-order state
    """

    draft = "draft"
    exported = "exported"
    in_progress = "in_progress"
    implemented = "implemented"
    validation_failed = "validation_failed"
    review_required = "review_required"
    approved = "approved"
    done = "done"
