# generated by datamodel-codegen:
#   filename:  work_order.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel

from . import execution_mode, work_order_status


class AcceptanceCriterion(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class ChangeReport(BaseModel):
    model_config = ConfigDict(extra="forbid")
    commit: Annotated[str | None, Field(pattern="^[a-f0-9]{7,40}$")] = None
    files_changed: list[FilesChangedItem]
    summary: str
    """
    Markdown text, rendered by the web app
    """
    written_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """


class Context(BaseModel):
    model_config = ConfigDict(extra="forbid")
    acceptance_criteria: Annotated[list[AcceptanceCriterion], Field(min_length=1)]
    expected_output: Annotated[list[ExpectedOutputItem], Field(min_length=1)]
    repository_paths: list[RepositoryPath]
    schemas: list[Schema]
    source_requirements: list[SourceRequirement]
    validation_commands: Annotated[list[ValidationCommand], Field(min_length=1)]


class Dependency(RootModel[str]):
    root: Annotated[str, Field(pattern="^HM-WO-\\d{4,}$")]


class Effort(StrEnum):
    xs = "xs"
    s = "s"
    m = "m"
    l = "l"
    xl = "xl"


class ExpectedOutputItem(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class FilesChangedItem(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class HistoryItem(BaseModel):
    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    by: Annotated[str, Field(max_length=120, min_length=1)]
    from_: Annotated[work_order_status.WorkOrderStatus | None, Field(alias="from")]
    note: Annotated[str | None, Field(max_length=500)] = None
    to: work_order_status.WorkOrderStatus


class Label(RootModel[str]):
    root: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]


class Priority(StrEnum):
    low = "low"
    normal = "normal"
    high = "high"


class RepositoryPath(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Schema(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class SourceRequirement(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Target(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["lesson"]
    lesson_id: Annotated[str, Field(pattern="^HM-LESSON-[a-z0-9-]+-\\d{2}$")]


class Target1(BaseModel):
    model_config = ConfigDict(extra="forbid")
    course_id: Annotated[str, Field(min_length=1)]
    kind: Literal["module"]
    module_id: Annotated[str, Field(min_length=1)]


class Target2(BaseModel):
    model_config = ConfigDict(extra="forbid")
    course_id: Annotated[str, Field(min_length=1)]
    kind: Literal["course"]


class Target3(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["skill"]
    skill_id: Annotated[str, Field(min_length=1)]


class Target4(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["problem"]
    problem_id: Annotated[
        str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")
    ]


class Target5(BaseModel):
    model_config = ConfigDict(extra="forbid")
    area: Annotated[str, Field(max_length=128, min_length=1, pattern="^[a-z0-9][a-z0-9._-]*$")]
    kind: Literal["platform"]


class Template(StrEnum):
    lesson_add = "lesson.add"
    lesson_update = "lesson.update"
    problem_create = "problem.create"
    platform_feature = "platform.feature"


class ValidationCommand(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class ValidationRun(BaseModel):
    model_config = ConfigDict(extra="forbid")
    at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    command: Annotated[str, Field(min_length=1)]
    exit_code: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]
    summary: Annotated[str, Field(max_length=2000)]


class WorkOrder(BaseModel):
    """
    Claude work order
    """

    model_config = ConfigDict(extra="forbid")
    change_report: ChangeReport | None = None
    context: Context
    created_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    dependencies: list[Dependency]
    effort: Effort | None = None
    execution: execution_mode.ExecutionMode
    history: list[HistoryItem]
    id: Annotated[str, Field(pattern="^HM-WO-\\d{4,}$")]
    instructions: str
    """
    Markdown text, rendered by the web app
    """
    labels: list[Label]
    priority: Priority
    requested_by: Annotated[str, Field(max_length=120, min_length=1)]
    status: work_order_status.WorkOrderStatus
    target: Target | Target1 | Target2 | Target3 | Target4 | Target5
    template: Template
    title: Annotated[str, Field(max_length=200, min_length=1)]
    updated_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
    validation_runs: list[ValidationRun]
