# generated by datamodel-codegen:
#   filename:  worker_envelope.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

from . import (
    destroy_job,
    error_event,
    exec_job,
    fault_inject_job,
    fault_verify_job,
    grade_job,
    heartbeat,
    log_event,
    provision_job,
    result_event,
    status_event,
)


class Kind(StrEnum):
    session_worker = "session_worker"
    lab_worker = "lab_worker"
    cli = "cli"


class Sender(BaseModel):
    model_config = ConfigDict(extra="forbid")
    id: Annotated[str, Field(max_length=120, min_length=1)]
    kind: Kind


class WorkerEnvelope(BaseModel):
    """
    Worker protocol envelope
    """

    model_config = ConfigDict(extra="forbid")
    correlation_id: Annotated[
        str | None,
        Field(pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"),
    ] = None
    message: Annotated[
        provision_job.ProvisionJob
        | exec_job.ExecJob
        | fault_inject_job.FaultInjectJob
        | fault_verify_job.FaultVerifyJob
        | grade_job.GradeJob
        | destroy_job.DestroyJob
        | status_event.StatusEvent
        | log_event.LogEvent
        | result_event.ResultEvent
        | error_event.ErrorEvent
        | heartbeat.Heartbeat,
        Field(title="WorkerMessage"),
    ]
    """
    Worker protocol message
    """
    message_id: Annotated[
        str,
        Field(pattern="^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"),
    ]
    protocol_version: Literal[1]
    sender: Sender
    sent_at: Annotated[
        str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,6})?Z$")
    ]
    """
    UTC instant in ISO-8601 with a trailing Z
    """
